### ISSUE TITLE
Add lynx clan's trackers to military units list

### ISSUE THREAD

**Issue by joeylmaalouf** [mCzolko/norsegod.club#16]
`[ 'Trackers', 25, 5 ],` in https://github.com/mCzolko/norsegod.club/blob/a00e7d07aa6e14195cf851d535b5ee98eeb9844c/src/pages/MilitaryUnitsPage.js#L8-L9

**Comment by mCzolko** [comment]
defo!

**Comment by mCzolko** [comment]
done
