### ISSUE TITLE
Sort clans by in-game order (release order) instead of alphabetically

### ISSUE THREAD

**Issue by joeylmaalouf** [mCzolko/norsegod.club#17]
On the lore page, where you list the clans, it goes `Bear, Boar, Dragon, Goat, Horse, Kraken, Lynx, Ox, Raven, Snake, Stag, Wolf`, but in-game it's `Wolf, Stag, Goat, Raven, Bear, Boar, Snake, Dragon, Horse, Kraken, Ox, Lynx`. I guess this isn't a real issue but it was weird to see them in a different order lol, reject this if you want.

Thank you for this website btw, it's like a combination of [this](https://northgard-lore-planner.netlify.app) and some useful spreadsheets!

**Comment by mCzolko** [comment]
will do

**Comment by mCzolko** [comment]
done
