### ISSUE TITLE
Add styling to the military chart to better differentiate unit types

### ISSUE THREAD

**Issue by joeylmaalouf** [mCzolko/norsegod.club#18]
The spacing between e.g. individual skirmishers and sum skirmishers is the same as the spacing between sum skirmishers and individual warriors. If that were adjusted or column borders were added, it would make the table a little easier to read at a glance when scrolling down to larger numbers.

![before](https://user-images.githubusercontent.com/5214728/105381274-d63a2680-5bdc-11eb-89ba-e9cf7c4bf060.png)
![after](https://user-images.githubusercontent.com/5214728/105381273-d63a2680-5bdc-11eb-9b3a-b154fe116e73.png)

**Comment by mCzolko** [comment]
ok, I'll come up with something

**Comment by mCzolko** [comment]
done
